default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: zerosploit-api_development

test:
  <<: *default
  database: zerosploit-api_test

production:
  <<: *default
  database: zerosploit-api_production
  username: zerosploit-api
  password: <%= ENV['ZEROSPLOIT-API_DATABASE_PASSWORD'] %>
